name: Deploy to Staging

on:
  push:
    branches: [stage]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_STAGE_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t iris-api .
        docker tag iris-api us-central1-docker.pkg.dev/mystic-song-461103-u9/iris-repo/iris-api:stage
        docker push us-central1-docker.pkg.dev/mystic-song-461103-u9/iris-repo/iris-api:stage

    - name: Set up kubectl for staging cluster
      run: |
        gcloud container clusters get-credentials iris-staging-cluster --zone us-central1-c --project mystic-song-461103-u9

    - name: Configure gke-gcloud-auth-plugin for kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Deploy to Staging
      run: |
        sed "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/mystic-song-461103-u9/iris-repo/iris-api:stage|" iris-deployment-template.yaml > iris-deployment.yaml
        kubectl apply -f iris-deployment.yaml
